### PR TITLE
Add Plan Popper Errors

### PR DESCRIPTION
**Pull request by imanmoreira**
Handled the following tickets:
https://trello.com/c/N0EP4QeB/180-create-plan-based-on-dropdown-border-overlaps-with-title-within-create-plan-popper
https://trello.com/c/x1p7LIAR/173-typo-in-create-plan-popper-when-creating-new-plan-from-existing-plan
https://trello.com/c/r8XKXASe/177-create-plan-popper-shows-an-error-when-submitting-without-setting-a-major
https://trello.com/c/yC39m66H/179-create-plan-popper-says-select-a-co-op-cycle-within-dropdown-for-selecting-an-existing-plan

### CODE REVIEW

**Comment by imanmoreira** [comment]
[Create plan popper says "Select A Co-op Cycle" within dropdown for selecting an existing plan](https://trello.com/c/yC39m66H/179-create-plan-popper-says-select-a-co-op-cycle-within-dropdown-for-selecting-an-existing-plan)

**Comment by imanmoreira** [comment]
[Create plan popper shows an error when submitting without setting a major](https://trello.com/c/r8XKXASe/177-create-plan-popper-shows-an-error-when-submitting-without-setting-a-major)

**Comment by imanmoreira** [comment]
[Typo in Create Plan Popper when creating new plan from existing plan](https://trello.com/c/x1p7LIAR/173-typo-in-create-plan-popper-when-creating-new-plan-from-existing-plan)

**Comment by imanmoreira** [comment]
["Create Plan Based On" Dropdown border overlaps with title within create plan popper](https://trello.com/c/N0EP4QeB/180-create-plan-based-on-dropdown-border-overlaps-with-title-within-create-plan-popper)

**Review by ArunJ98 — APPROVED** [review]

**Pull request merged**
