### PR TITLE
Bug confirm password

### PR DESCRIPTION
**Pull request by rael346**
# Description

Bug fix for sign up screen where users can sign up without filling out the confirm password field.

https://user-images.githubusercontent.com/75349763/157754053-ff7ab1a5-4324-4ac2-8db5-fe68e89f2daf.mov

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] On Sign Up screen, enter email and password, but leave out the confirm password field (don't click or tab on it). Click "Sign Up" and there should be an error "Confirm Password is required".

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by aryanshah701 — APPROVED** [review]
looks good to me!

**Review by jia614 — APPROVED** [review]
wanted to try a pr kek but it works on my end and looks good to meee

**Review by bugsalexander — APPROVED** [review]
YEET

**Review by cindy1u0 — APPROVED** [review]
LGTM!

**Pull request merged**
