### PR TITLE
Advisor dev bypass button

### PR DESCRIPTION
**Pull request by NilsBacke**

### CODE REVIEW

**Comment by NilsBacke** [comment]
[Add Dev Bypass button for logging in as an advisor](https://trello.com/c/mXWF66lY/237-add-dev-bypass-button-for-logging-in-as-an-advisor)

**Review by imanmoreira — APPROVED** [review]

**Review by imanmoreira — CHANGES_REQUESTED** [review]
I'm having some bugs with the redirection. For the student button, it's redirecting to the advising pages and for the advising pages the redirecting isn't working (the link it's routed to is /undefined)

**Comment by NilsBacke** [comment]
Very weird, I just tried mine again and it worked fine. I just rebased and fixed some conflicts so maybe that'll fix it. Otherwise you can try deleting the user from your db and trying again and see if that makes any difference.

**Review by imanmoreira — APPROVED** [review]
Yeah I'm not sure what happened last time but it's looking good! Sorry about that

**Pull request merged**
