### PR TITLE
base years in schedule off academic year and graduation year

### PR DESCRIPTION
**Pull request by NilsBacke**

### CODE REVIEW

**Comment by NilsBacke** [comment]
[When given the initial schedule, the years are not based off your academic year/graduation year](https://trello.com/c/2aMaptdz/156-when-given-the-initial-schedule-the-years-are-not-based-off-your-academic-year-graduation-year)

**Review by imanmoreira — COMMENTED** [review]
I don't think this is working correctly (?)
The initial schedule is no longer loading for me, and it doesn't show the years when I try to select a new plan

**Review by ArunJ98 — APPROVED** [review]

**Comment by ArunJ98** [comment]
lgtm, you have some merge conflicts tho

**Comment by NilsBacke** [comment]
This problem seems to be a little more complicated than initially planned, will put this on hold for now until we iron out some loose ends in the code.

**Pull request closed without merging**
